name: README build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16

    steps:
      - name: Checkout repository
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: node update.js
      - name: Commit
        run: |-
          git add .
          git diff
          git config --global user.email "ronaldosuman97@gmail.com"
          git config --global user.name "sumanbiswas7"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push
